In [6]:
# Weather Data Analysis
#This notebook contains the analysis of the weather dataset to answer specific questions.

In [8]:
import pandas as pd

# Load the dataset
file_path = '1. Weather Data.csv'
df = pd.read_csv(file_path)

## Question 1
Find all records where the weather was exactly clear.

In [39]:
clear_weather_records = df[df['Weather_Condition'] == 'Clear']
clear_weather_records

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

## Question 2
Find the number of times the wind speed was exactly 4 km/hr.

In [37]:
wind_speed_count = df[df['Wind Speed_km/h'] == 4].shape[0]
wind_speed_count

474

## Question 3
Check if there are any NULL values present in the dataset

In [14]:
null_values = df.isnull().sum()
null_values

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

## Question 4
Rename the column "Weather" to "Weather_Condition."

In [76]:
df.rename(columns={'Weather': 'Weather_Condition'}, inplace=True)
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

## Question 5
What is the mean visibility of the dataset?

In [41]:
mean_visibility = df['Visibility_km'].mean()
mean_visibility

27.664446721311478

# Question 6
Find the number of records where the wind speed is greater than 24 km/hr and visibility is equal to 25 km.y

In [43]:
records_count = df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)].shape[0]
records_count

308

# Question 7
What is the mean value of each column for each weather condition?

In [88]:
mean_values_by_weather = df.groupby('Weather_Condition').mean()
mean_values_by_weather

TypeError: agg function failed [how->mean,dtype->object]

# Question 8
Find all instances where the weather is clear and the relative humidity is greater than 50, or visibility is above 40.

In [86]:
filtered_records = df[(df['Weather_Condition'] == 'Clear') & ((df['Rel Hum_%'] > 50) | (df['Visibility_km'] > 40))]
filtered_records

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

# Question 9
Find the number of weather conditions that include snow.

In [32]:

snow_conditions_count = df['Weather_Condition'].str.contains('Snow', case=False).sum()
snow_conditions_count

583

In [90]:
df.dtypes

Date/Time             object
Temp_C               float64
Dew Point Temp_C     float64
Rel Hum_%              int64
Wind Speed_km/h        int64
Visibility_km        float64
Press_kPa            float64
Weather_Condition     object
dtype: object